### ISSUE TITLE
CR 13 is not supported

### ISSUE THREAD

**Issue by bxsx** [alocshrestha/Crystal_API#1]
Hi,

sorry to open a new issue here but couldn't find your email. I have to generate some reports via CR and  found your repository. The SAP documentation is really bad and just have a question. Did you try to run it on CR 12 or CR 13? It seems like CrystalRunTime.Application doesn't exist any more. Do you have any idea how to update the code?

**Comment by alocshrestha** [comment]
Hi @bartskowron, oh this has been a while! At the time of building this api, i was using an older version of CR. (I am guessing either CR 9 or 10). I believe you can still use older dlls for CR and call the Application function for there. (I know it seems like a lot of work).  I found the below link. Hope it helps.

https://www.tektutorialshub.com/how-to-download-and-install-crystal-report-runtime/

**Comment by alocshrestha** [comment]
Hi @bartskowron, oh this has been a while! At the time of building this api, i was using an older version of CR. (I am guessing either CR 9 or 10). I believe you can still use older dlls for CR and invoke the Application module from there. (I know it seems like a lot of work). I found the below link. Hope this helps.

https://www.tektutorialshub.com/how-to-download-and-install-crystal-report-runtime/
