### ISSUE TITLE
error dispacth in version 11

### ISSUE THREAD

**Issue by amry666** [alocshrestha/Crystal_API#2]
i was installed Crystal Report XI version 11..0.0.895, but when i try to Dispatch("CrystalRuntime.Application") got error (-2147221005, 'Invalid class string', None, None). how to solve this?

**Comment by amry666** [comment]
solved by reinstalling to version Crystal Reports XI Release 2 SP4. make sure "CrystalRuntime.Application" registered in regedit.

**Comment by alocshrestha** [comment]
Thank you for update, apology for the delay in response but yes most of these runtime errors can be resolved with appropriate version install.
